version: 0.0
os: linux
files:
  - source: /
    destination: /home/deploy/adenio/releases
permissions:
  - object: /home/deploy/adenio/releases
    owner: deploy
    group: deploy
    pattern: "*"
    mode: 775
    type:
      - file
      - directory
hooks:
  AfterInstall:
    - location: deployment_scripts/after_intall.sh
      runas: deploy
