version: 0.0
os: linux
files:
  - source: /
    destination: /home/deploy/adenio/releases/adenio
permissions:
  - object: /home/deploy/adenio/releases/adenio
    owner: deploy
    group: deploy
    mode: 777
    type: 
      - directory
hooks:
  AfterInstall:
    - location: deployment_scripts/after_install.sh
      runas: deploy
  ApplicationStart:
    - location: deployment_scripts/application_start.sh
      runas: deploy
